# Dependencies from install-zsh.sh
brew "bat"
brew "direnv"
brew "eza"
brew "fd"
brew "fx"
brew "git"
brew "git-delta"
brew "htop"
brew "jq"
brew "pyenv"
brew "rnr"
brew "ripgrep"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "zx"

# Keep homebrew up to date
brew "terminal-notifier"

# NerdFonts
cask "font-meslo-lg-nerd-font"

# UI Programs
cask "anki"
cask "brave-browser"
cask "brave-browser@beta"
brew "bitwarden"
brew "bitwarden-cli"
cask "boop"
cask "chromedriver"
cask "claude-code"
cask "cursor"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "firefox"
cask "ghostty"
cask "maestral"
cask "obsidian"
cask "shottr"
cask "slack"
cask "sonos"
cask "spotify"
cask "tunnelblick"
cask "vlc"
cask "zoom"
