export CLICOLOR=1
export EDITOR="vim"
export HISTCONTROL=ignoreboth # don't put duplicate lines in the history. See bash(1) for more options
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help" # Make some commands not show up in history
export LANG="en_US" # Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8" # Prefer US English and use UTF-8
export LSCOLORS='Gxfxcxdxdxegedabagacad'
export MANPAGER="less -X" # Don’t clear the screen after quitting a manual page
export PATH=$HOME/go/bin:$HOME/.yarn/bin:$HOME/bin:$HOME/.iterm4:$PATH

# append to the history file, don't override it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

set completion-ignore-case on # Make Tab autocomplete regardless of filename case
set page-completions off # Immediately show all possible completions
set show-all-if-ambiguous off # List all matches in case multiple possible completions are possible, overrides *-unmodified
set show-all-if-unmodified on # List all matches with nicer prefix rules when multiple completions are possible
set skip-completed-text on # Be more intelligent when autocompleting by also looking at the text after the cursor.

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# this was helpful: http://misc.flogisoft.com/bash/tip_colors_and_formatting
BLUE='\[\033[1;36m\]'
BOLD='\[\033[1m\]'
DIM='\[\033[2m\]'
GREEN='\[\033[32m\]'
ORANGE='\[\033[93m\]'
RED='\[\033[31m\]'
UNDIM='\[\033[22m\]'
WHITE='\[\033[00m\]'

alias less='less -R'
os="`uname`"
if [ $os == "Darwin" ]; then
	alias ls='CLICOLOR_FORCE=1 ls -G'
	alias subl='subl -a -n'
	alias dotfiles='subl ~/.dotFiles'
else
	alias ls='LC_COLLATE=C ls --color'
	PS1=$GREEN'\u'$DIM'@'$UNDIM$BOLD$ORANGE'\h'$WHITE': '$BLUE'\w'$RED'$(__git_ps1 " (%s)")'$WHITE'$ '
fi

function source_file() {
	if [ -f $1 ]; then
		source $1
		return 1
	fi
	return 0
}

source_file "$HOME/.bash_profile.local"
source_file "$HOME/.ssh/saveagent"

source_file "$HOME/bin/iterm2_shell_integration.bash"
source_file "$HOME/bin/arcanist/resources/shell/bash-completion"
source_file "$HOME/bin/pages-gem/contrib/func.sh"
source_file "$HOME/.nvm/nvm.sh"
source_file "$HOME/.nvm/bash_completion"

if arc help &> /dev/null ; then
  arc set-config base 'arc:verbose, arc:amended, git:merge-base(master)' > /dev/null
fi

# FZF with the_silver_searcher
export FZF_DEFAULT_COMMAND='ag --ignore *.pyc -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

if brew -h &> /dev/null; then
	brew_prefix=`brew --prefix`

	source_file "$brew_prefix/etc/bash_completion.d/brew"
	source_file "$brew_prefix/etc/bash_completion.d/flow-completion.bash"
	source_file "$(brew --prefix git)/etc/bash_completion.d/git-completion.bash"
	source_file "$brew_prefix/etc/bash_completion.d/npm"
	source_file "$brew_prefix/etc/bash_completion.d/tig-completion.bash"
	source_file "$brew_prefix/etc/bash_completion.d/tmux"

	source_file "$brew_prefix/opt/fzf/shell/completion.bash"
	source_file "$brew_prefix/opt/fzf/shell/key-bindings.bash"

	source_file "/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion"
	source_file "/Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion"
	source_file "/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion"

	if [ -f "$(brew --prefix git)/etc/bash_completion.d/git-prompt.sh" ]; then
		source "$(brew --prefix git)/etc/bash_completion.d/git-prompt.sh"

		PS1=$GREEN'\u'$DIM'@'$UNDIM'\h'$WHITE': '$BLUE'\w'$RED'$(__git_ps1 " (%s)")'$WHITE'$ '
	fi
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
# This is after HomeBrew fzf/shell/completion.bash so we can include hosts from ~/.ssh/config.local
if [ -f "$HOME/.ssh/config" ]; then
	ssh_hosts=$(grep --no-filename "^Host" $HOME/.ssh/config $HOME/.ssh/config.local | grep -v "[?*]" | cut -d " " -f2)
	complete  -o "nospace" -W "$ssh_hosts" scp sftp ssh
fi

function json() {
  python -mjson.tool <<< "$*" | pygmentize -l javascript
}
