"" General

set number  " Show line numbers
set cursorline  " highlight current line
set showmatch   " Highlight matching brace
set visualbell  " Use visual bell (no beeping)

set ruler   " Show row and column ruler information
set showtabline=2   " Show tab bar
set autowriteall    " Auto-write all file changes

set undolevels=1000 " Number of undo levels
set backspace=indent,eol,start  " Backspace behaviour

set foldmethod=indent " fold based on indent level
set foldlevel=10 " fold the 10th indent

"" Tabs

filetype indent on  " load filetype-specific indent files from places like `~/.vim/indent/python.vim`

set autoindent  " Auto-indent new lines
set shiftwidth=2    " Number of auto-indent spaces
set smartindent " Enable smart-indent
set smarttab    " Enable smart-tabs
set softtabstop=2   " Number of spaces per Tab
set tabstop=2       " number of visual spaces per TAB


"" Search

set hlsearch    " Highlight all search results
set ignorecase  " Always case-insensitive
set incsearch   " Searches for strings incrementally
set smartcase   " Enable smart-case search


"" Colors

syntax enable
colorscheme monokai


"" UI

set wildmenu " visual autocomplete for command menu
