#!/usr/bin/env zsh
set -e

OS="$(uname)"

case $OS in
  Darwin)
    echo 'Include ./config.darwin'
    echo 'Include ./config.local'
  ;;
  Linux)
    echo 'Include ./config.linux'
    echo 'Include ./config.local'
  ;;
esac
